services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cctv_layout
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "55432:55432"

  redis:
    image: redis:7-alpine
    ports:
      - "56379:56379"

  backend:
    build:
      context: ./backend
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: cctv_layout
      TYPEORM_LOGGING: "true"
      REALTIME_PATH: /realtime
      ALLOWED_ORIGINS: http://localhost:5173
      REDIS_HOST: redis
      REDIS_PORT: 56379
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    command: sh -c "npm install && npm run start:dev"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"

volumes:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:
